
import React from 'react';
import { Language } from '../types.ts';

interface DisclaimerProps {
  language: Language;
}

const Disclaimer: React.FC<DisclaimerProps> = ({ language }) => {
  const text = language === 'si' 
    ? "වගකීම් ප්‍රකාශය: මෙම අනාවැකි සහ උපදෙස් කෘතිම බුද්ධිය (AI) මගින් ජනනය කරන ලද්දකි. මෙම තොරතුරු විනෝදාස්වාදය සඳහා පමණක් වන අතර වෘත්තීය උපදෙස් වෙනුවට භාවිතා නොකරන්න."
    : "Disclaimer: These predictions and insights are generated by artificial intelligence. This information is for entertainment purposes only and should not be used as a substitute for professional legal, medical, or financial advice.";

  return (
    <div className="mt-8 mb-4 px-4 py-4 rounded-xl border border-white/5 text-center max-w-2xl mx-auto bg-white/5 backdrop-blur-sm">
      <p className="text-[10px] md:text-[11px] text-white/30 leading-relaxed uppercase tracking-wider font-medium">
        {text}
      </p>
    </div>
  );
};

export default Disclaimer;
