
import React from 'react';
import { Language } from '../../types.ts';

interface DisclaimerProps {
  language: Language;
}

const Disclaimer: React.FC<DisclaimerProps> = ({ language }) => {
  const text = language === 'si' 
    ? "වගකීම් ප්‍රකාශය: මෙම අනාවැකි සහ උපදෙස් කෘතිම බුද්ධිය (AI) මගින් වේද ශාස්ත්‍රානුකූලව ජනනය කරන ලද්දකි. මෙම තොරතුරු වෘත්තීය නීති, වෛද්‍ය, හෝ මූල්‍ය උපදෙස් සඳහා ප්‍රතිස්ථානයක් ලෙස භාවිතා කළ යුතු නොවේ."
    : "Disclaimer: These predictions and insights are generated by artificial intelligence according to Vedic methods. This information should not be used as a substitute for professional legal, medical, or financial advice.";

  return (
    <div className="mt-8 mb-4 px-4 py-4 rounded-xl border border-white/5 text-center max-w-2xl mx-auto bg-white/5 backdrop-blur-sm">
      <p className="text-[10px] md:text-[11px] text-white/30 leading-relaxed uppercase tracking-wider font-medium">
        {text}
      </p>
    </div>
  );
};

export default Disclaimer;
